spring: #띄어쓰기 없음
  datasource: #띄어쓰기 2칸
    url: jdbc:h2:tcp://localhost/~/advancedBookService #4칸
    username: sa
    password:
    driver-class-name: org.h2.Driver
  #     url : jdbc:mysql://localhost:3306/AdBookService
  #     username : root
  #     password : root
  #     driver-class-name: com.mysql.cj.jdbc.Driver

  jpa: #띄어쓰기 2칸
    hibernate: #띄어쓰기 4칸
      ddl-auto: create #띄어쓰기 6칸
    properties: #띄어쓰기 4칸
      hibernate: #띄어쓰기 6칸
        # show_sql: true #띄어쓰기 8칸
        #        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true #띄어쓰기 8칸
  devtools:
    restart:
      exclude: static/** #유저 이미지가 추가 될때마다 새로운 파일 추가로 restart 방지
  servlet:
    multipart:
        max-file-size: 2MB

#logging.level: #띄어쓰기 없음
#  org.hibernate.SQL: debug #띄어쓰기 2칸

server:
  servlet:
    session:
      tracking-modes: cookie
#      timeout : 10
#세션 정보가 url에 노출되지 않도록

file:
  dir: C:\\Users\\HYEONMO\\Desktop\\GitHub\\advanced-bookservice\\bookservice\\src\\main\\resources\\memberData\\
  default-dir: C:\\Users\\HYEONMO\\Desktop\\GitHub\\advanced-bookservice\\bookservice\\src\\main\\resources\\static\\img\\